name: Build APK

on:               # ← ESTA sección es la que faltaba
  workflow_dispatch:   # permite lanzarlo manualmente
  push:                # (opcional) se ejecuta cada push a main
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Instalar dependencias de sistema
      run: |
        sudo apt update
        sudo apt install -y python3-pip zip unzip openjdk-17-jdk

    - name: Instalar Buildozer
      run: pip install buildozer cython==0.29.36

    - name: Construir APK
      run: buildozer android debug

    - name: Publicar APK como artefacto
      uses: actions/upload-artifact@v3
      with:
        name: stc_detector.apk
        path: bin/*.apk
# Este comentario fuerza a Git a ver un cambio