name: Build APK

on:
  push:
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    # --- instalar Buildozer con SDK y licencias ---
    - name: Construir APK
      run: |
        cd src
        buildozer init || true
        cp ../buildozer.spec .
        
        # Instalar herramientas necesarias
        sudo apt update
        sudo apt install -y openjdk-17-jdk wget unzip

        # Instalar command line tools (porque Build-Tools 36 ya no se puede usar sin aceptar licencia)
        mkdir -p $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdtools.zip
        unzip cmdtools.zip -d $HOME/android-sdk/cmdline-tools
        export PATH=$HOME/android-sdk/cmdline-tools/cmdline-tools/bin:$PATH

        # Aceptar licencias
        yes | sdkmanager --sdk_root=$HOME/android-sdk --licenses || true

        # Construir APK
        buildozer android debug

    # --- compilar APK ---
    - name: Build debug APK
      run: |
        export ANDROID_HOME=$HOME/android
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/cmdline-tools/bin:$ANDROID_HOME/platform-tools
        yes | buildozer -v android debug

    # --- subir artefacto ---
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: stc-detector-debug
        path: bin/*.apk
